create table spots
(
    sp_id           serial
        primary key,
    sp_name         varchar(60) not null,
    sp_location     geometry,
    sp_price        boolean,
    sp_bio          varchar(400),
    sp_verification boolean       default false,
    sp_views        integer       default 0,
    sp_st_id        integer
        constraint spots_spot_types_st_id_fk
            references spot_types,
    sp_tel          varchar(20),
    sp_email        varchar(40),
    sp_description  varchar(1000) default 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia, molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium optio, eaque rerum! Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut! Impedit sit sunt quaerat, odit, tenetur error, harum nesciunt ipsum debitis quas aliquid. Reprehenderit, quia. Quo neque error repudiandae fuga? Ipsa laudantium molestias eos  sapiente officiis modi at sunt excepturi expedita sint? Sed quibusdam recusandae alias error harum maxime adipisci amet laborum.'::character varying
);

alter table spots
    owner to bqqiwhxdlkihkz;

INSERT INTO public.spots (sp_id, sp_name, sp_location, sp_price, sp_bio, sp_verification, sp_views, sp_st_id, sp_tel, sp_email, sp_description) VALUES (2, 'IADE teste', '0101000000F939F4CC815A43403E29EED34C4E22C0', false, 'comida', false, 400, 2, '913548325', 'teste4@gmail.com', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia, molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium optio, eaque rerum! Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut! Impedit sit sunt quaerat, odit, tenetur error, harum nesciunt ipsum debitis quas aliquid. Reprehenderit, quia. Quo neque error repudiandae fuga? Ipsa laudantium molestias eos  sapiente officiis modi at sunt excepturi expedita sint? Sed quibusdam recusandae alias error harum maxime adipisci amet laborum.');
INSERT INTO public.spots (sp_id, sp_name, sp_location, sp_price, sp_bio, sp_verification, sp_views, sp_st_id, sp_tel, sp_email, sp_description) VALUES (1, 'IADE teste', '0101000000F939F4CC815A43403E29EED34C4E22C0', false, 'Discoteca', true, 322, 3, '913548325', 'teste4@gmail.com', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia, molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium optio, eaque rerum! Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut! Impedit sit sunt quaerat, odit, tenetur error, harum nesciunt ipsum debitis quas aliquid. Reprehenderit, quia. Quo neque error repudiandae fuga? Ipsa laudantium molestias eos  sapiente officiis modi at sunt excepturi expedita sint? Sed quibusdam recusandae alias error harum maxime adipisci amet laborum.');
INSERT INTO public.spots (sp_id, sp_name, sp_location, sp_price, sp_bio, sp_verification, sp_views, sp_st_id, sp_tel, sp_email, sp_description) VALUES (3, 'Bar Careca', '01010000001E882CD2C45A4340C21B2D62336722C0', false, 'bare para carecas', false, 1059, 1, '962548321', 'teste1@gmail.com', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia, molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium optio, eaque rerum! Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut! Impedit sit sunt quaerat, odit, tenetur error, harum nesciunt ipsum debitis quas aliquid. Reprehenderit, quia. Quo neque error repudiandae fuga? Ipsa laudantium molestias eos  sapiente officiis modi at sunt excepturi expedita sint? Sed quibusdam recusandae alias error harum maxime adipisci amet laborum.');
INSERT INTO public.spots (sp_id, sp_name, sp_location, sp_price, sp_bio, sp_verification, sp_views, sp_st_id, sp_tel, sp_email, sp_description) VALUES (4, 'Rest Monte verde 1111', '0101000000B0F4EB98045C434026BD14C37A6C22C0', false, 'rest', true, 127, 2, '958423658', 'teste3@gmail.com', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia, molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium optio, eaque rerum! Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut! Impedit sit sunt quaerat, odit, tenetur error, harum nesciunt ipsum debitis quas aliquid. Reprehenderit, quia. Quo neque error repudiandae fuga? Ipsa laudantium molestias eos  sapiente officiis modi at sunt excepturi expedita sint? Sed quibusdam recusandae alias error harum maxime adipisci amet laborum.');
INSERT INTO public.spots (sp_id, sp_name, sp_location, sp_price, sp_bio, sp_verification, sp_views, sp_st_id, sp_tel, sp_email, sp_description) VALUES (23, 'teste com imagem', '01010000003E7D5FB7635B434021B5E44C6E5322C0', null, '  sdfsdfsdfsdfsd', false, 0, 3, '966187313', 'freitasalmeidalda@gmail.com', '  sdfsdfsdfsdfsd');
INSERT INTO public.spots (sp_id, sp_name, sp_location, sp_price, sp_bio, sp_verification, sp_views, sp_st_id, sp_tel, sp_email, sp_description) VALUES (16, 'Erva', '0101000000893A1856965E43400A0A28791A7922C0', false, 'comida', false, 0, 2, '987654321', '5@mail.com', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia, molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium optio, eaque rerum! Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut! Impedit sit sunt quaerat, odit, tenetur error, harum nesciunt ipsum debitis quas aliquid. Reprehenderit, quia. Quo neque error repudiandae fuga? Ipsa laudantium molestias eos  sapiente officiis modi at sunt excepturi expedita sint? Sed quibusdam recusandae alias error harum maxime adipisci amet laborum.');
INSERT INTO public.spots (sp_id, sp_name, sp_location, sp_price, sp_bio, sp_verification, sp_views, sp_st_id, sp_tel, sp_email, sp_description) VALUES (13, 'Magnetic', '0101000000D4F9A69F265E434074D190F1284D22C0', false, 'comida', false, 0, 2, '987654321', 'b@mail.com', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia, molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium optio, eaque rerum! Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut! Impedit sit sunt quaerat, odit, tenetur error, harum nesciunt ipsum debitis quas aliquid. Reprehenderit, quia. Quo neque error repudiandae fuga? Ipsa laudantium molestias eos  sapiente officiis modi at sunt excepturi expedita sint? Sed quibusdam recusandae alias error harum maxime adipisci amet laborum.');
INSERT INTO public.spots (sp_id, sp_name, sp_location, sp_price, sp_bio, sp_verification, sp_views, sp_st_id, sp_tel, sp_email, sp_description) VALUES (12, 'Central Da Estrela', '0101000000C6EC1B4E4F5B4340D3A23EC91D5222C0', false, 'comida', false, 0, 2, '987654321', 'a@mail.com', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia, molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium optio, eaque rerum! Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut! Impedit sit sunt quaerat, odit, tenetur error, harum nesciunt ipsum debitis quas aliquid. Reprehenderit, quia. Quo neque error repudiandae fuga? Ipsa laudantium molestias eos  sapiente officiis modi at sunt excepturi expedita sint? Sed quibusdam recusandae alias error harum maxime adipisci amet laborum.');
INSERT INTO public.spots (sp_id, sp_name, sp_location, sp_price, sp_bio, sp_verification, sp_views, sp_st_id, sp_tel, sp_email, sp_description) VALUES (14, 'Os meninos ', '0101000000A8D205ABA06043402A5CEA7B688222C0', false, 'comida', false, 0, 2, '987654321', 'c@mail.com', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia, molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium optio, eaque rerum! Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut! Impedit sit sunt quaerat, odit, tenetur error, harum nesciunt ipsum debitis quas aliquid. Reprehenderit, quia. Quo neque error repudiandae fuga? Ipsa laudantium molestias eos  sapiente officiis modi at sunt excepturi expedita sint? Sed quibusdam recusandae alias error harum maxime adipisci amet laborum.');
INSERT INTO public.spots (sp_id, sp_name, sp_location, sp_price, sp_bio, sp_verification, sp_views, sp_st_id, sp_tel, sp_email, sp_description) VALUES (15, '3 Em Cena', '0101000000A8D205ABA06043402A5CEA7B688222C0', false, 'comida', false, 0, 2, '987654321', 'teste06@mail.com', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia, molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium optio, eaque rerum! Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut! Impedit sit sunt quaerat, odit, tenetur error, harum nesciunt ipsum debitis quas aliquid. Reprehenderit, quia. Quo neque error repudiandae fuga? Ipsa laudantium molestias eos  sapiente officiis modi at sunt excepturi expedita sint? Sed quibusdam recusandae alias error harum maxime adipisci amet laborum.');
INSERT INTO public.spots (sp_id, sp_name, sp_location, sp_price, sp_bio, sp_verification, sp_views, sp_st_id, sp_tel, sp_email, sp_description) VALUES (19, 'freitas almeida lda.', '01010000003E7D5FB7635B434021B5E44C6E5322C0', null, 'sfdujvbhoscnvljscnv lçksdjoiwdsj vuhsf  uh sccov h sdfou hdfsolh dfhv fjnsdjn vscjnv dkcjnv fskljmn sdkh sdfn sdskudhv sdunhv sdvh sdvh wsdhf oasdu hfkidfuhf kisua bkidrfsuihikuw gfsdi ufesdiuygbgvn', false, 2, 3, '966187313', 'freitasalmeidalda@gmail.com', 'sfdujvbhoscnvljscnv lçksdjoiwdsj vuhsf  uh sccov h sdfou hdfsolh dfhv fjnsdjn vscjnv dkcjnv fskljmn sdkh sdfn sdskudhv sdunhv sdvh sdvh wsdhf oasdu hfkidfuhf kisua bkidrfsuihikuw gfsdi ufesdiuygbgvn');
INSERT INTO public.spots (sp_id, sp_name, sp_location, sp_price, sp_bio, sp_verification, sp_views, sp_st_id, sp_tel, sp_email, sp_description) VALUES (31, 'Urben beach', '01010000003E7D5FB7635B434021B5E44C6E5322C0', null, 'fgadiusaifjiusdbvnd x idufhn iudh fysdh v iusdh  viusdh vous hvois doiouiw dvoiuiwdniuifmvoiui wifuh wdoiui wdoiuoiu woiuoh weiuhff iweu hf', false, 0, 3, '966187313', 'freitasalmeidalda@gmail.com', 'fgadiusaifjiusdbvnd x idufhn iudh fysdh v iusdh  viusdh vous hvois doiouiw dvoiuiwdniuifmvoiui wifuh wdoiui wdoiuoiu woiuoh weiuhff iweu hf');
INSERT INTO public.spots (sp_id, sp_name, sp_location, sp_price, sp_bio, sp_verification, sp_views, sp_st_id, sp_tel, sp_email, sp_description) VALUES (20, 'rthdfm,nvnfknb,lb,vb,.nvc,.bvcb', '01010000006209B5F00661434019FD6838654E22C0', null, '', false, 0, 3, '966187313', 'leonardolage10@gmail.com', '');
INSERT INTO public.spots (sp_id, sp_name, sp_location, sp_price, sp_bio, sp_verification, sp_views, sp_st_id, sp_tel, sp_email, sp_description) VALUES (21, 'i coiso so hard', '01010000006209B5F00661434019FD6838654E22C0', null, '', false, 0, 3, '966187313', 'leonardolage10@gmail.com', '');
INSERT INTO public.spots (sp_id, sp_name, sp_location, sp_price, sp_bio, sp_verification, sp_views, sp_st_id, sp_tel, sp_email, sp_description) VALUES (17, 'O Madeirense ', '01010000003EEEB666865C4340641CC81FB17622C0', false, 'comida', false, 1, 2, '987654321', '6@mail.com', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia, molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium optio, eaque rerum! Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut! Impedit sit sunt quaerat, odit, tenetur error, harum nesciunt ipsum debitis quas aliquid. Reprehenderit, quia. Quo neque error repudiandae fuga? Ipsa laudantium molestias eos  sapiente officiis modi at sunt excepturi expedita sint? Sed quibusdam recusandae alias error harum maxime adipisci amet laborum.');
INSERT INTO public.spots (sp_id, sp_name, sp_location, sp_price, sp_bio, sp_verification, sp_views, sp_st_id, sp_tel, sp_email, sp_description) VALUES (22, 'i coisxcvo so hardxvc', '01010000006209B5F00661434019FD6838654E22C0', null, '', false, 0, 3, '966187313', 'leonardolage10@gmail.com', '');
INSERT INTO public.spots (sp_id, sp_name, sp_location, sp_price, sp_bio, sp_verification, sp_views, sp_st_id, sp_tel, sp_email, sp_description) VALUES (24, 'freitas almeida lda.', '01010000003E7D5FB7635B434021B5E44C6E5322C0', null, '', false, 0, null, '', 'freitasalmeidalda@gmail.com', '');
INSERT INTO public.spots (sp_id, sp_name, sp_location, sp_price, sp_bio, sp_verification, sp_views, sp_st_id, sp_tel, sp_email, sp_description) VALUES (25, 'freitas almeida lda.', '01010000003E7D5FB7635B434021B5E44C6E5322C0', null, '', false, 0, null, '966187313', 'freitasalmeidalda@gmail.com', '');
INSERT INTO public.spots (sp_id, sp_name, sp_location, sp_price, sp_bio, sp_verification, sp_views, sp_st_id, sp_tel, sp_email, sp_description) VALUES (26, 'freitas almeida lda.', '01010000003E7D5FB7635B434021B5E44C6E5322C0', null, '', false, 0, 2, '966187313', 'freitasalmeidalda@gmail.com', '');
INSERT INTO public.spots (sp_id, sp_name, sp_location, sp_price, sp_bio, sp_verification, sp_views, sp_st_id, sp_tel, sp_email, sp_description) VALUES (27, 'freitas almeida lda.', '01010000003E7D5FB7635B434021B5E44C6E5322C0', null, '', false, 0, 3, '966187313', 'freitasalmeidalda@gmail.com', '');
INSERT INTO public.spots (sp_id, sp_name, sp_location, sp_price, sp_bio, sp_verification, sp_views, sp_st_id, sp_tel, sp_email, sp_description) VALUES (28, 'tentativa nao sei das quantas ', '01010000003E7D5FB7635B434021B5E44C6E5322C0', null, '', false, 1, 3, '12431241231', 'freitasalmeidalda@gmail.com', '');
INSERT INTO public.spots (sp_id, sp_name, sp_location, sp_price, sp_bio, sp_verification, sp_views, sp_st_id, sp_tel, sp_email, sp_description) VALUES (18, 'leonardo rodrigues', '01010000006209B5F00661434019FD6838654E22C0', null, 'batatata', false, 23, 3, '966187313', 'leonardolage10@gmail.com', 'batatata');
INSERT INTO public.spots (sp_id, sp_name, sp_location, sp_price, sp_bio, sp_verification, sp_views, sp_st_id, sp_tel, sp_email, sp_description) VALUES (29, 'v2323234234234234234234', '01010000003E7D5FB7635B434021B5E44C6E5322C0', null, '', false, 2, 3, '', 'freitasalmeidalda@gmail.com', '');
INSERT INTO public.spots (sp_id, sp_name, sp_location, sp_price, sp_bio, sp_verification, sp_views, sp_st_id, sp_tel, sp_email, sp_description) VALUES (32, 'qualquer coisa', '01010000003E7D5FB7635B434021B5E44C6E5322C0', null, '123123', false, 0, 1, '12312', 'freitasalmeidalda@gmail.com', '123123');
INSERT INTO public.spots (sp_id, sp_name, sp_location, sp_price, sp_bio, sp_verification, sp_views, sp_st_id, sp_tel, sp_email, sp_description) VALUES (30, 'freitas almeida lda.', '01010000003E7D5FB7635B434021B5E44C6E5322C0', null, '', false, 3, 1, '', 'freitasalmeidalda@gmail.com', '');
